"""
author: Aidan Lone, Husnain Sidhu, Muhammad Ali, Malaz Nakaweh, Dabeer Awan
date: January 12, 2026
purpose: Database for compound characteristics and chemical formulas
"""
compound_list = {
        #   {COMPOUND NAME}: [({CHEMICAL FORMULA}), {NUMBER OF ATOMS}, {TYPE OF COMPOUND}, {ENTHALPY OF FORMATION}]
            "Methane": [("CH4"), 5, "Organic (Alkane)", -74.4],
            "Ethane": [("C2H6"), 8, "Organic (Alkane)", -84.68],
            "Benzene": [("C6H6"), 12, "Aromatic (Hydrocarbon)", +49.1],
            "Carbon Dioxide": [("CO2"), 3, "Covalent", -393.5],
            "Carbon Monoxide": [("CO"), 2, "Covalent", -110.53],
            "Ammonia": [("NH3"), 4, "Covalent", -45.9],
            "Hydrochloric Acid": [("HCl"), 3, "Molecular", -92.3],
            "Silver Bromide": [("AgBr"), 2, "Ionic", -100.37],
            "Silver Chloride": [("AgCl"), 2, "Ionic", -127.1],
            "Aluminum Chloride": [("AlCl3"), 4, "Covalent", -704],
            "Calcium Oxide": [("CaO"), 2, "Ionic", -635],
            "Sodium Chloride": [("NaCl"), 2, "Ionic", -411],
            "Water": [("H2O"), 3, "Covalent", -285.83],
            "Hydrogen Peroxide": [("H2O2"), 4, "Covalent", -187.8],
            "Sulfuric Acid": [("H2SO4"), 7, "Molecular", -814],
            "Nitric Acid": [("HNO3"), 5, "Molecular", -207],
            "Sodium Hydroxide": [("NaOH"), 3, "Ionic", -425.6],
            "Potassium Chloride": [("KCl"), 2, "Ionic", -436.7],
            "Calcium Carbonate": [("CaCO3"), 5, "Ionic", -1206.9],
            "Sodium Carbonate": [("Na2CO3"), 6, "Ionic", -1130.7],
            "Magnesium Oxide": [("MgO"), 2, "Ionic", -601.6],
            "Silicon Dioxide": [("SiO2"), 3, "Covalent Network", -910.9],
            "Ethanol": [("C2H5OH"), 9, "Organic (Alcohol)", -277.7],
            "Propane": [("C3H8"), 11, "Organic (Alkane)", -103.8],
            "Butane": [("C4H10"), 14, "Organic (Alkane)", -125.6],
            "Acetic Acid": [("CH3COOH"), 8, "Organic (Carboxylic Acid)", -484.5],
}


# List of chemical formulas that will react in Reaction Lab
chemical_formula_list = ["AgAt", "AgBr", "AgCl", "AgF", "AgI", 
                         "AuAt", "AuBr", "AuCl", "AuF", "AuI", 
                         "BaAt", "BaBr", "BaCl", "BaF", "BaI",
                         "BeAt", "BeBr", "BeCl", "BeF", "BeI",
                         "BiAt", "BiBr", "BiCl", "BiF", "BiI",
                         "CaAt", "CaBr", "CaCl", "CaF", "CaI",
                         "CdAt", "CdBr", "CdCl", "CdF", "CdI",
                         "CoAt", "CoBr", "CoCl", "CoF", "CoI",
                         "CrAt", "CrBr", "CrCl", "CrF", "CrI",
                         "CsAt", "CsBr", "CsCl", "CsF", "CsI",
                         "CuAt", "CuBr", "CuCl", "CuF", "CuI",
                         "FeAt", "FeBr", "FeCl", "FeF", "FeI",
                         "FrAt", "FrBr", "FrCl", "FrF", "FrI",
                         "HgAt", "HgBr", "HgCl", "HgF", "HgI",
                         "KAt", "KBr", "KCl", "KF", "KI",
                         "LiAt", "LiBr", "LiCl", "LiF", "LiI",
                         "MgAt", "MgBr", "MgCl", "MgF", "MgI",
                         "MnAt", "MnBr", "MnCl", "MnF", "MnI",
                         "NaAt", "NaBr", "NaCl", "NaF", "NaI",
                         "NiAt", "NiBr", "NiCl", "NiF", "NiI",
                         "PbAt", "PbBr", "PbCl", "PbF", "PbI",
                         "PtAt", "PtBr", "PtCl", "PtF", "PtI",
                         "RaAt", "RaBr", "RaCl", "RaF", "RaI",
                         "RbAt", "RbBr", "RbCl", "RbF", "RbI",
                         "SbAt", "SbBr", "SbCl", "SbF", "SbI",
                         "SnAt", "SnBr", "SnCl", "SnF", "SnI",
                         "SrAt", "SrBr", "SrCl", "SrF", "SrI",
                         "ZnAt", "ZnBr", "ZnCl", "ZnF", "ZnI" ]


# List of compound names that will react in Reaction Lab
chemical_name_list = ["Silver Astatide", "Silver Bromide", "Silver Chloride", "Silver Fluoride", "Silver Iodide",
                      "Gold Astatide", "Gold Bromide", "Gold Chloride", "Gold Fluoride", "Gold Iodide",
                      "Barium Astatide", "Barium Bromide", "Barium Chloride", "Barium Fluoride", "Barium Iodide",
                      "Beryllium Astatide", "Beryllium Bromide", "Beryllium Chloride", "Beryllium Fluoride", "Beryllium Iodide",
                      "Bismuth Astatide", "Bismuth Bromide", "Bismuth Chloride", "Bismuth Fluoride", "Bismuth Iodide",
                      "Calcium Astatide", "Calcium Bromide", "Calcium Chloride", "Calcium Fluoride", "Calcium Iodide",
                      "Cadmium Astatide", "Cadmium Bromide", "Cadmium Chloride", "Cadmium Fluoride", "Cadmium Iodide",
                      "Cobalt Astatide", "Cobalt Bromide", "Cobalt Chloride", "Cobalt Fluoride", "Cobalt Iodide",
                      "Chromium Astatide", "Chromium Bromide", "Chromium Chloride", "Chromium Fluoride", "Chromium Iodide",
                      "Cesium Astatide", "Cesium Bromide", "Cesium Chloride", "Cesium Fluoride", "Cesium Iodide",
                      "Copper Astatide", "Copper Bromide", "Copper Chloride", "Copper Fluoride", "Copper Iodide",
                      "Iron Astatide", "Iron Bromide", "Iron Chloride", "Iron Fluoride", "Iron Iodide",
                      "Francium Astatide", "Francium Bromide", "Francium Chloride", "Francium Fluoride", "Francium Iodide",
                      "Mercury Astatide", "Mercury Bromide", "Mercury Chloride", "Mercury Fluoride", "Mercury Iodide",
                      "Potassium Astatide", "Potassium Bromide", "Potassium Chloride", "Potassium Fluoride", "Potassium Iodide",
                      "Lithium Astatide", "Lithium Bromide", "Lithium Chloride", "Lithium Fluoride", "Lithium Iodide",
                      "Magnesium Astatide", "Magnesium Bromide", "Magnesium Chloride", "Magnesium Fluoride", "Magnesium Iodide",
                      "Manganese Astatide", "Manganese Bromide", "Manganese Chloride", "Manganese Fluoride", "Manganese Iodide",
                      "Sodium Astatide", "Sodium Bromide", "Sodium Chloride", "Sodium Fluoride", "Sodium Iodide",
                      "Nickel Astatide", "Nickel Bromide", "Nickel Chloride", "Nickel Fluoride", "Nickel Iodide",
                      "Lead Astatide", "Lead Bromide", "Lead Chloride", "Lead Fluoride", "Lead Iodide",
                      "Platinum Astatide", "Platinum Bromide", "Platinum Chloride", "Platinum Fluoride", "Platinum Iodide",
                      "Radium Astatide", "Radium Bromide", "Radium Chloride", "Radium Fluoride", "Radium Iodide",
                      "Rubidium Astatide", "Rubidium Bromide", "Rubidium Chloride", "Rubidium Fluoride", "Rubidium Iodide",
                      "Antimony Astatide", "Antimony Bromide", "Antimony Chloride", "Antimony Fluoride", "Antimony Iodide",
                      "Tin Astatide", "Tin Bromide", "Tin Chloride", "Tin Fluoride", "Tin Iodide",
                      "Strontium Astatide", "Strontium Bromide", "Strontium Chloride", "Strontium Fluoride", "Strontium Iodide",
                      "Zinc Astatide", "Zinc Bromide", "Zinc Chloride", "Zinc Fluoride", "Zinc Iodide"]
